HGGM/Controllers/AuditController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using HGGM.Models;
using HGGM.Services;
using HGGM.Services.Authorization;
using HGGM.Services.Authorization.Simple;
using HGGM.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace HGGM.Controllers
{
    [Permission(SimplePermissionType.GetAuditLog)]
    public class AuditController : Controller
    {
        private readonly AuditService _auditService;

        public AuditController(AuditService auditService)
        {
            _auditService = auditService;
        }

        public IActionResult Details(Guid id)
        {
            var entry = _auditService.Get(id);
            var props = new Dictionary<string, string>();
            foreach (var propertyInfo in entry.GetType().GetProperties(BindingFlags.Public | BindingFlags.Instance))
            {
                var name = propertyInfo.Name;
                if (propertyInfo.CanRead == false || name == nameof(AuditEntryBase.Id) ||
                    name == nameof(AuditEntryBase.Message) || name == nameof(AuditEntryBase.Time)) continue;
                var value = propertyInfo.GetValue(entry);
                if (value is string s)
                    props.Add(name, s);
                else
                    props.Add(name, JsonConvert.SerializeObject(value));
            }

            return View(new AuditDetailsViewModel
                {Id = entry.Id, Time = entry.Time, Properties = props, message = entry.Message});
        }

        // GET: Audit
        public IActionResult Index()
        {
            return View(_auditService.GetAll());
        }
    }
}

HGGM/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HGGM.Models.Audit;
using HGGM.Models.Identity;
using HGGM.Services;
using HGGM.Services.Authorization;
using HGGM.Services.Authorization.Simple;
using HGGM.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace HGGM.Controllers
{
    [Permission(SimplePermissionType.GetRoles)]
    public class RolesController : Controller
    {
        private readonly AuditService _auditService;
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<Role> _roleManager;

        public RolesController(RoleManager<Role> roleManager, AuditService auditService, UserManager<User> userManager)
        {
            this._roleManager = roleManager;
            _auditService = auditService;
            _userManager = userManager;
        }

        [Permission(SimplePermissionType.EditRoles)]
        public ActionResult Create()
        {
            return View();
        }

        [Permission(SimplePermissionType.EditRoles)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("Name")] Role role)
        {
            if (ModelState.IsValid)
            {
                var result = await _roleManager.CreateAsync(role);
                _auditService.Add(new RoleAudit()
                {
                    Role = role.Name,
                    RoleId = role.Id,
                    Type = "created",
                    User = _userManager.GetUserName(User),
                    UserId = _userManager.GetUserId(User)
                });

                foreach (var error in result.Errors) ModelState.AddModelError(string.Empty, error.Description);
                if (result.Succeeded) return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [Permission(SimplePermissionType.EditRoles)]
        public async Task<ActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            return View(role);
        }

        [Permission(SimplePermissionType.EditRoles)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(Role role)
        {
            var roleName = await _roleManager.FindByIdAsync(role.Id);
            await _roleManager.DeleteAsync(role);
            _auditService.Add(new RoleAudit()
            {
                Role = roleName.Name,
                Type = "deleted",
                RoleId = role.Id,
                User = _userManager.GetUserName(User),
                UserId = _userManager.GetUserId(User)
            });
            return RedirectToAction(nameof(Index));
        }


        public async Task<ActionResult> Details(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            return View(role);
        }

        [Permission(SimplePermissionType.EditRoles)]
        public async Task<ActionResult> Edit(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            var m = new EditRoleViewModel
            {
                Name = role.Name, SimplePermissions = SimplePermission.GetAllSimplePermissions.ToDictionary(
                    k => k.Permission.ToString(),
                    v => role.Permissions?.OfType<SimplePermission>()?.Contains(v) ?? false)
            };

            return View(m);
        }

        [Permission(SimplePermissionType.EditRoles)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([FromRoute] string id, [FromForm] EditRoleViewModel model)
        {
            if (!ModelState.IsValid) return View(model);
            // Get original role
            var role = await _roleManager.FindByIdAsync(id);
            // Change properties
            role.Name = model.Name;
            var before = role.Permissions ?? new List<IPermission>();
            var after = model.SimplePermissions
                .Where(p => p.Value).Select(p =>
                    new SimplePermission(Enum.Parse<SimplePermissionType>(p.Key)));
            role.Permissions = before
                .Where(p => p.GetType() != typeof(SimplePermission))
                .Concat(after)
                .ToList();
            //Save
            var result = await _roleManager.UpdateAsync(role);

            foreach (var error in result.Errors) ModelState.AddModelError(string.Empty, error.Description);

            if (!result.Succeeded) return View(model);

            _auditService.Add(new RoleEditAudit
            {
                User = _userManager.GetUserName(User), UserId = _userManager.GetUserId(User), Role = role.Name,
                Type = "changed",
                RoleId = role.Id,
                Before = JsonConvert.SerializeObject(before, Formatting.Indented),
                After = JsonConvert.SerializeObject(after, Formatting.Indented)
            });

            return RedirectToAction(nameof(Index));
        }

        public ActionResult Index()
        {
            return View(_roleManager.Roles.ToList());
        }
    }
}

HGGM/Controllers/TagsController.cs
using System;
using System.Linq;
using HGGM.Models;
using HGGM.Models.Audit;
using HGGM.Models.Identity;
using HGGM.Services;
using HGGM.Services.Authorization;
using HGGM.Services.Authorization.Simple;
using LiteDB;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace HGGM.Controllers
{
    [Permission(SimplePermissionType.GetTags)]
    public class TagsController : Controller
    {
        private readonly LiteRepository db;
        private readonly AuditService _audit;
        private readonly UserManager<User> _userManager;

        public TagsController(LiteRepository db, AuditService audit, UserManager<User> userManager)
        {
            this.db = db;
            _audit = audit;
            _userManager = userManager;
        }

        [Permission(SimplePermissionType.EditTags)]
        public ActionResult Create()
        {
            return View();
        }

        [Permission(SimplePermissionType.EditTags)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("TagName")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Insert(tag);
                _audit.Add(new TagAudit()
                {
                    Tag = tag.TagName,
                    TagId = tag.Id.ToString(),
                    Type = "created",
                    User = _userManager.GetUserName(User),
                    UserId = _userManager.GetUserId(User)
                });
                return RedirectToAction(nameof(Index));
            }

            return View();
        }


        [Permission(SimplePermissionType.EditTags)]
        public ActionResult Delete(Guid id)
        {
            var tag = db.SingleById<Tag>(id);
            return View(tag);
        }

        [Permission(SimplePermissionType.EditTags)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete([Bind(nameof(Tag.Id))] [FromRoute] Tag tag)
        {
            var tagId = tag.Id;
            var tagObj = db.SingleById<Tag>(tag.Id);
            db.Delete<Tag>(tagId);

            _audit.Add(new TagAudit()
            {
                Tag = tagObj.TagName,
                TagId = tag.Id.ToString(),
                Type = "deleted",
                User = _userManager.GetUserName(User),
                UserId = _userManager.GetUserId(User)
            });

            return RedirectToAction(nameof(Index));
        }

        public ActionResult Details(Guid id)
        {
            var tag = db.SingleById<Tag>(id);
            return View(tag);
        }

        [Permission(SimplePermissionType.EditTags)]
        public ActionResult Edit(Guid id)
        {
            var tag = db.SingleById<Tag>(id);
            return View(tag);
        }

        [Permission(SimplePermissionType.EditTags)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Tag tag)
        {
            if (ModelState.IsValid)
            {
                var tagOld = db.SingleById<Tag>(tag.Id);
                var before = JsonConvert.SerializeObject(tagOld, Formatting.Indented);
                db.Update(tag);
                _audit.Add(new TagEditAudit()
                {
                    Tag = tagOld.TagName,
                    TagId = tag.Id.ToString(),
                    Before = before,
                    After = JsonConvert.SerializeObject(tag, Formatting.Indented),
                    Type = "changed",
                    User = _userManager.GetUserName(User),
                    UserId = _userManager.GetUserId(User)
                });
                return RedirectToAction(nameof(Index));
            }

            return View(tag);
        }

        public ActionResult Index()
        {
            var tags = db.Fetch<Tag>();
            return View(tags);
        }
    }
}

HGGM/Controllers/UsersController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HGGM.Models.Audit;
using HGGM.Models.Identity;
using HGGM.Services;
using HGGM.Services.Authorization;
using HGGM.Services.Authorization.Simple;
using HGGM.ViewModels;
using LiteDB;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace HGGM.Controllers
{
    [Permission(SimplePermissionType.GetUsers)]
    public class UsersController : Controller
    {
        private readonly List<string> _countryList = CultureService.GetCountries();
        private readonly LiteRepository _db;
        private readonly RoleManager<Role> _roleManager;
        private readonly UserManager<User> _userManager;
        private readonly AuditService _audit;
        private readonly SignInManager<User> _signInManager;

        public UsersController(UserManager<User> userManager, RoleManager<Role> roleManager, LiteRepository db, AuditService audit, SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _db = db;
            _audit = audit;
            _signInManager = signInManager;
        }

        [Permission(SimplePermissionType.EditUsers)]
        public async Task<ActionResult> Delete(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            return View(user);
        }

        [Permission(SimplePermissionType.EditUsers)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(string id, IFormCollection collection)
        {       
            var user = await _userManager.FindByIdAsync(id);
            var before = JsonConvert.SerializeObject(user);
            await _userManager.DeleteAsync(user);
            _audit.Add(new AdminEditUserAudit()
            {
                Before = before,
                After = "User Deleted",
                EditedUser = user.UserName,
                EditedUserId = user.Id,
                Type = "deleted",
                User = _userManager.GetUserName(User),
                UserId = _userManager.GetUserId(User)
            });

            return RedirectToAction(nameof(Index));
        }

        public async Task<ActionResult> Details(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            var roles = _roleManager.Roles
                .Select(r => r.Name)
                .ToDictionary(r => r, r => user.Roles.Contains(r));
            return View(new EditUserViewModel
            {
                User = user,
                Roles = roles,
                Email = user.Email.Address
            });
        }

        [Permission(SimplePermissionType.EditUsers)]
        public async Task<ActionResult> Edit(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            var roles = _roleManager.Roles
                .Select(r => r.Name)
                .ToDictionary(r => r, r => user.Roles.Contains(r));
            return View(new EditUserViewModel
            {
                Roles = roles,
                User = user,
                CountryList = _countryList,
                Email = user.Email.Address
            });
        }

        private User EditUser(User db, User edited)
        {
            db.UserName = edited.UserName;
            db.Name = edited.Name;
            db.Biography = edited.Biography;
            db.Country = edited.Country;
            db.DateOfBirth = edited.DateOfBirth;
            db.JoinDate = edited.JoinDate;
            db.TeamspeakUID = edited.TeamspeakUID;
            db.Headline = edited.Headline;
            return db;
        }

        [Permission(SimplePermissionType.EditUsers)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string id, EditUserViewModel uvm)
        {
            if (!ModelState.IsValid) return View(uvm);

            var user = EditUser(await _userManager.FindByIdAsync(id), uvm.User);
            var userOld = _userManager.FindByIdAsync(id);
            var before = JsonConvert.SerializeObject(user, Formatting.Indented);
            user.Email = uvm.Email;
            user.Roles = uvm.Roles.Where(r => r.Value).Select(h => h.Key).ToList();

            var result = await _userManager.UpdateAsync(user);

            _audit.Add(new AdminEditUserAudit()
            {
                Before = before,
                EditedUser = userOld.Result.UserName,
                EditedUserId = user.Id,
                Type = "edited",
                After = JsonConvert.SerializeObject(user, Formatting.Indented),
                User = _userManager.GetUserName(User),
                UserId = _userManager.GetUserId(User)
            });
            if (result.Succeeded)
            {
                await _signInManager.RefreshSignInAsync(user);
                if (uvm.RemoveAvatar)
                {
                    _db.FileStorage.Delete(user.Id);
                }
                return RedirectToAction(nameof(Index));
            }
            foreach (var error in result.Errors) ModelState.AddModelError(error.Code, error.Description);

            return View(uvm);
        }

        public ActionResult Index()
        {
            var users = _db.Fetch<User>(collectionName: "users").ToList();
            return View(users);
        }
    }
}

HGGM/Views/Shared/_Layout.cshtml
@using System.Threading
@using Microsoft.AspNetCore.Http.Extensions
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Configuration
@using Microsoft.Extensions.DependencyInjection
@inject IViewLocalizer Localizer
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HGGM</title>

    <link rel="stylesheet" href="~/lib/bulma/css/bulma.min.css" />
    <link rel="stylesheet" href="~/lib/datatables-bulma/css/dataTables.bulma.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome-5-css/css/all.min.css" />
    <link rel="stylesheet" href="~/lib/jquery-datetimepicker/jquery.datetimepicker.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

</head>
<body>


<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" asp-area="" asp-controller="Home" asp-action="Index">
            <img src="https://417rct.org/themes/fabriciorabelo-squad/assets/images/417LogoPath.svg" height="28">
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item" asp-area="" asp-controller="Home" asp-action="Index">
                Events
            </a>

            <a class="navbar-item" asp-area="" asp-controller="Home" asp-action="Index">
                Videos
            </a>

            <a class="navbar-item" asp-area="" asp-controller="Home" asp-action="Index">
                Donate
            </a>

            <a class="navbar-item" asp-area="" asp-controller="Home" asp-action="Index">
                Status
            </a>
            @foreach (var link in Context.RequestServices.GetService<IConfiguration>().GetSection("Links").GetChildren())
            {
                <a class="navbar-item" href="@link.Value">
                    <markdown>@link.Key</markdown>
                </a>
            }
            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                    More
                </a>

                <div class="navbar-dropdown">
                    <a class="navbar-item" asp-area="" asp-controller="Users" asp-action="Index">
                        Users
                    </a>
                    <a class="navbar-item" asp-area="" asp-controller="Roles" asp-action="Index">
                        Roles
                    </a>
                    <a class="navbar-item" asp-area="" asp-controller="Tags" asp-action="Index">
                        Tags
                    </a>
                    <a class="navbar-item" asp-area="" asp-controller="Audit" asp-action="Index">
                        Audit
                    </a>
                    <a class="navbar-item" asp-area="" asp-controller="Events" asp-action="PublishedIndex">
                        Events
                    </a>
                    <hr class="navbar-divider">
                    <a class="navbar-item" href="/hangfire">
                        HangFire
                    </a>
                    <a class="navbar-item" href="/swagger">
                        Swagger
                    </a>
                </div>
            </div>
        </div>

        <div class="navbar-end">
            <partial name="_LoginPartial"/>
        </div>
    </div>
</nav>

<section class="section">
    <div class="container">
        @RenderBody()
    </div>
</section>
<hr/>
<footer class="footer">
    <details class="content">
        <summary>&copy; 2018 - HGGM</summary>
        <dl>
            <dt>Request</dt>
            <dd><span class="tag">@Context.Request.GetDisplayUrl()</span> at <span class="tag">@DateTimeOffset.Now.ToString()</span></dd>
            @if (User.Identity.IsAuthenticated)
            {
                <dt>User</dt>
                <dd>
                    @foreach (var c in User.Claims)
                    {
                        <span class="tag">@c.Type.Split('.', '/').Last()='@c.Value'</span>
                    }
                </dd>
            }
            <dt>User languages</dt>
            <dd>
                <span class="tag">@Context.Request.Headers["Accept-Language"].ToString()</span>
            </dd>
            <dt>Server language</dt>
            <dd>Culture: <span class="tag">@Thread.CurrentThread.CurrentCulture</span>, UI: <span class="tag">@Thread.CurrentThread.CurrentCulture</span></dd>
            <dt>Chosen language</dt>
            @{
                var rf = Context.Features.Get<IRequestCultureFeature>();
                var culture = rf.RequestCulture.Culture;
                var uiCulture = rf.RequestCulture.UICulture;
                var setBy = rf.Provider?.GetType().Name;
            }
            <dd>Culture: <span class="tag">@culture</span>, UI: <span class="tag">@uiCulture</span>, Set by: <span class="tag">@setBy</span></dd>
        </dl>
    </details>
</footer>

<script src="~/lib/jquery/jquery.min.js"></script>
<script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
<script src="~/lib/datatables-bulma/js/dataTables.bulma.min.js"></script>
<script src="~/lib/jquery-datetimepicker/jquery.datetimepicker.full.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
    
@RenderSection("Scripts", false)

<partial name="_CookieConsentPartial" />

</body>
</html>